export const ROWS = [
  {
    id: 1,
    name: "Test",
    listenerId:"2c99c8d9-56fa-4970-9d45-4448cff00dd8",
    protocol: "HTTP",
    port: "80",
    operatingStatus: "Active",
    provisioningStatus: "Active",
    adminState: "Up",
    autoScalingMember: "No",
    createdAt: "09-09-2025 11:33",
    listenderId: "2345dfgv-dfghbvb-fgfgfg-dfghghh-dfghjkkkkl",
    description: "test",
  },
  {
    id: 2,
    name: "Test",
    protocol: "HTTP",
    port: "80",
    operatingStatus: "Active",
    provisioningStatus: "Active",
    adminState: "Up",
    autoScalingMember: "No",
    createdAt: "09-09-2025 11:33",
    listenderId: "2345dfgv-dfghbvb-fgfgfg-dfghghh-dfghjkkkkl",
    description: "test",
  },
  {
    id: 3,
    name: "Test",
    protocol: "HTTP",
    port: "80",
    operatingStatus: "Active",
    provisioningStatus: "Active",
    adminState: "Up",
    autoScalingMember: "No",
    createdAt: "09-09-2025 11:33",
    listenderId: "2345dfgv-dfghbvb-fgfgfg-dfghghh-dfghjkkkkl",
    description: "test",
  },
];
