export const ROWS = [
  {
    id: 1,
    alertName: "High Usage Alert",
    status: "Active",
    metricType: "CPU Utilization",
    metricField: "CPU Usage",
    criticalThreshold: "",
    warningThreshold: "60%",
    resourceName: "Dummy",
    notificationChannel: "Email",
    resourceId: "fghj-fghj-dfgh-dfghjk",
    description: "Testing postman",
    lastRunStatus: "",
    createdAt: "13-09-2025 13:56",
    updatedAt: "13-09-2025 13:56",
  },
  {
    id: 2,
    alertName: "High Usage Alert",
    status: "Active",
    metricType: "CPU Utilization",
    metricField: "CPU Usage",
    criticalThreshold: "",
    warningThreshold: "60%",
    resourceName: "Dummy",
    notificationChannel: "Email",
    resourceId: "fghj-fghj-dfgh-dfghjk",
    description: "Testing postman",
    lastRunStatus: "",
    createdAt: "13-09-2025 13:56",
    updatedAt: "13-09-2025 13:56",
  },
  {
    id: 3,
    alertName: "High Usage Alert",
    status: "Active",
    metricType: "CPU Utilization",
    metricField: "CPU Usage",
    criticalThreshold: "",
    warningThreshold: "60%",
    resourceName: "Dummy",
    notificationChannel: "Email",
    resourceId: "fghj-fghj-dfgh-dfghjk",
    description: "Testing postman",
    lastRunStatus: "",
    createdAt: "13-09-2025 13:56",
    updatedAt: "13-09-2025 13:56",
  },
];
