import type { Metadata } from "next";
import { Readex_Pro } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/components/Toast/ToastProvider";

const readexPro = Readex_Pro({
  subsets: ["latin"],
  variable: "--font-readex",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${readexPro.className} antialiased`}>
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
