export const ROWS = [
  {
    id: 1,
    name: "Test",
    protocol: "HTTP",
    algorithm: "Round Robin",
    operatingStatus: "Error",
    provisioningStatus: "Active",
    adminState: "Up",
    autoScalingMember: "No",
    tlsEnabled: "No",
    createdAt: "09-09-2025 11:33",
    poolId: "adf34webcj237-asfyu32",
    description: "test",
  },
  {
    id: 2,
    name: "Test",
    protocol: "HTTP",
    algorithm: "Round Robin",
    operatingStatus: "Error",
    provisioningStatus: "Active",
    adminState: "Up",
    autoScalingMember: "No",
    tlsEnabled: "No",
    createdAt: "09-09-2025 11:33",
    poolId: "fghj-fghj-fgh-fgh-dfgh",
    description: "test",
  },
  {
    id: 3,
    name: "Test",
    protocol: "HTTP",
    algorithm: "Round Robin",
    operatingStatus: "Error",
    provisioningStatus: "Active",
    adminState: "Up",
    autoScalingMember: "No",
    tlsEnabled: "No",
    createdAt: "09-09-2025 11:33",
    poolId: "fghj-fghj-fgh-fgh-dfgh",
    description: "test",
  },
];
