export const ROWS = [
  {
    id: 1,
    name: "Test",
    ipAddress: "45.194.3.216",
    subnet: "EXT-Sub-NOI-3",
    port: "test",
    elasticIp: "",
    operatingStatus: "Error",
    provisioningStatus: "Active",
    adminState: "Up",
    autoScalingMember: "No",
    createdAt: "09-09-2025 11:33",
    loadbalancerId: "fgh-dfgh-dfghj-dfghjk-dfghj",
    description: "description",
  },
  {
    id: 2,
    name: "Test",
    ipAddress: "45.194.3.216",
    subnet: "EXT-Sub-NOI-3",
    port: "test",
    elasticIp: "",
    operatingStatus: "Error",
    provisioningStatus: "Active",
    adminState: "Up",
    autoScalingMember: "No",
    createdAt: "09-09-2025 11:33",
    loadbalancerId: "fgh-dfgh-dfghj-dfghjk-dfghj",
    description: "description",
  },
  {
    id: 3,
    name: "Test",
    ipAddress: "45.194.3.216",
    subnet: "EXT-Sub-NOI-3",
    port: "test",
    elasticIp: "",
    operatingStatus: "Error",
    provisioningStatus: "Active",
    adminState: "Up",
    autoScalingMember: "No",
    createdAt: "09-09-2025 11:33",
    loadbalancerId: "fgh-dfgh-dfghj-dfghjk-dfghj",
    description: "description",
  },
];
